### ISSUE TITLE
Add access to the hello page in Firefox

### ISSUE THREAD

**Issue by dit7ya** [posobin/ampie#2]
I cannot access the hello page after update. It would be nice to put the link to that from the extensions manager descriptions or something.

**Comment by posobin** [comment]
Yeah, the link on ampie.app is for chrome. I haven't updated the firefox version in a while, the hello page will open automatically once updated. Hope that will release a new version today or tomorrow, both for firefox and chrome.

**Comment by posobin** [comment]
The hello page is now at https://ampie.app/hello, it should pop up when ampie updates for you.
