### ISSUE TITLE
firefox: issues with link extraction

### ISSUE THREAD

**Issue by karlicoss** [posobin/ampie#4]
On https://news.ycombinator.com/

![image](https://user-images.githubusercontent.com/291333/99871466-cef19f00-2bd2-11eb-8c79-00d81612a2ee.png)

In comparison, chrome:
![image](https://user-images.githubusercontent.com/291333/99871456-b84b4800-2bd2-11eb-9289-7b2ac6bfb6fb.png)

Ampersand badges don't seem to show either in Firefox.

Both addon versions are 2.3.1

**Comment by posobin** [comment]
This is interesting. Could you uninstall ampie and install again, if this wasn't a fresh install? Also the styles are broken in firefox for you for some reason, very weird.

**Comment by karlicoss** [comment]
No, wasn't a fresh install. Indeed, uninstalling and installing back fixed it.. odd!

**Comment by posobin** [comment]
Is the styling the same as chrome now? In the first screenshot the headers of sections are not bold, and the font is not Roboto as it should be (looks like Ubuntu's standard sans-serif?). Is that the case after reinstall?

**Comment by karlicoss** [comment]
Hmm, on a more careful inspection -- yeah not really (I'm pretty font-blind :) )

![image](https://user-images.githubusercontent.com/291333/99884941-700b4480-2c29-11eb-8d3e-7c001628c303.png)

Interesting enough, if I just set `font: 10pt Roboto`, it changes to Roboto.. don't quite remember how the font resolution works.
For the `font-weight`, I remember encountering similar issues, basically it's only well-defined only for certain values, at least in Firefox. For example, `600` (like in the `:before` selector) works. I personally just resorted to using `bold/bolder` for this reason, less headache :)

**Comment by posobin** [comment]
Does the new update fix this? The font should be "source sans pro" now, probably the problem was because I was using chrome-specific urls in the css file with fonts. Yes, there can be problems with font weights, but the extension comes with the fonts of necessary weights, so should be ok.

**Comment by karlicoss** [comment]
Yep, looks good! 
![image](https://user-images.githubusercontent.com/291333/100000292-4bde6d80-2db9-11eb-96da-9a6428c9a001.png)
